# Generated by Django 4.1.2 on 2022-10-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_tag_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
