# Generated by Django 4.1.2 on 2022-10-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_tag_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
    ]
