# Generated by Django 4.1.2 on 2022-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_remove_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='photos.tag'),
        ),
    ]
