# Generated by Django 4.1.2 on 2022-10-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='photo',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.category'),
        ),
    ]
