# Generated by Django 4.1.2 on 2022-10-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_category_alter_photo_title_photo_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='tag_name',
        ),
    ]
