# Generated by Django 4.1.2 on 2022-10-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_rename_tagname_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='category',
        ),
    ]
