# Generated by Django 4.1.2 on 2022-10-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_series_remove_photo_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='series',
        ),
        migrations.AddField(
            model_name='photo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.serie'),
        ),
    ]
