# Generated by Django 4.1.2 on 2022-10-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_rename_series_serie_remove_photo_series_photo_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['id'], 'verbose_name': 'Цикл фотографий', 'verbose_name_plural': 'Циклы фотографий'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация о фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.serie', verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ser_name',
            field=models.CharField(max_length=100, verbose_name='Цикл'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тег'),
        ),
    ]
