# Generated by Django 4.1.2 on 2022-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_alter_photo_options_alter_serie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
