# Generated by Django 4.1.2 on 2022-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_serie_slug_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
